[project]
name = "english-bot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.129.0",
    "sqlalchemy>=2.0.46",
    "uvicorn>=0.40.0",
]
